const en = {
    
  'Top.Title': 'Rookie Training 2019',
  'Button.Category': 'Categories',
  'Menu.Item': 'Items',
  'Menu.Staff': 'Staff',
  'Menu.Title': 'Change Language',
  'Menu.Japanese': 'Japanese',
  'Menu.English': 'English',
  'Menu.SingOut': 'Sign Out',
  'Button.Create': 'Create',
  'Button.Edit': 'Edit',
  'Button.Delete': 'Delete',
  'Button.Submit': 'Submit',
  'Button.Cancel': 'Cancel',
  'Label.SignIn': 'Sign In',
  'Button.SignIn': 'Sign In',
  'Label.SignUp': 'Sign Up',
  'Button.SignUp': 'Sign Up',
  'Confirm.TextTitle': 'Are you sure?',
  'Confirm.TextBody' : 'Do you really want to delete',
  'Menu.SingIn': 'Sign In',
  'Menu.OrderHistory': 'Order History',
  'Label.Category': 'Categories',
  'Button.Add': 'Add Button',
  'Button.Confirm': 'Confirm',
  'Label.ForgotPassword': 'Forgot Password',
  'Label.NotAccount': 'No Account?SignUp?',
  'Button.CreateAccount': 'CreateAccount',
  'Label.AlreadyAccount': 'Already have an account? Sign in',
  'Label.SendCode': 'Send Code',
  'Label.BackSignin': 'Back to Signin ',
  'Label.PasswordReset': 'Reset Password',
  'Label.CheckEmail': 'Please check your email',
  'Label.ResendCode': 'Send Code to ',
  'Label.Product': 'Product',
  'Label.Description': 'Description',
  'Label.Quantity': 'Quantity',
  'Label.Price': 'Price',
  'Label.CartList': 'Cart List',
  'Label.TotalPrice': 'Total Price',
  'Label.TotalQuantity': 'Total Quantity',
  'Label.Tax': 'Sales Tax',
  'Label.SubTotal': 'SubTotal',
   'Label.Information': 'Information',
   'Label.ShippingInformation': 'Shipping Information',
   'Label.InformationDetail': 'Please fill your information fully',
   'Button.Shopping': 'Shopping',
   'Label.OrderConfirm': 'Order Confirmation',
   'Label.OrderReview': 'Order Review',
   'Button.Close': 'Close',
   'Link.Detail': 'Detail',
   'Button.Back': 'Back',
   'Label.OrderText': '**You can seach order list by order id**',
   'Label.DateText': '**You can seach order list by date**',
    'Label.OrderSuccess': 'Your Order is Complete...Success...!',
   'Label.OrderSuccessId': 'Your Order Id is',
    'Label.InfoDetail': 'Detail  Information',
    'Label.Image': 'Image',
    'Label.OrderHistory': 'Order History',
     
 

  
};
export default en;
