const ja = {
  'Top.Title': '新人研修作品2019',
   'Button.Category': 'カテゴリー',
  'Menu.Item': 'アイテム',
  'Menu.Staff': 'スタッフ',
  'Menu.Title': '言語を変更',
  'Menu.Japanese': '日本語',
  'Menu.English': '英語',
  'Menu.SingOut': 'ログアウト',
  'Button.Create': '作成',
  'Button.Edit': '編集',
  'Button.Delete': '削除',
  'Button.Submit': '送信',
  'Button.Cancel': 'キャンセル',
  'Label.SignIn': 'サインイン',
  'Button.SignIn': 'サインイン',
  'Label.SignUp': 'サインアップ',
  'Button.SignUp': 'サインアップ',
  'Confirm.TextTitle': '削除の確認',
  'Confirm.TextBody' : '本当に削除しますか？',
  'Menu.SingIn': 'サインイン',
  'Menu.OrderHistory': '注文履歴',
  'Label.Category': 'カテゴリー',
  'Button.Add': '追加ボタン',
  'Button.Confirm': '確認',
  'Label.ForgotPassword': 'パスワードをお忘れる?',
  'Label.NotAccount': 'アカウントない?サインアップ?',
  'Button.CreateAccount': 'アカウントを作成する',
  'Label.AlreadyAccount': 'すでにアカウントをお持ちですか？サインイン',
  'Label.SendCode': 'コードを送信',
  'Label.BackSignin': 'サインインに戻る ',
  'Label.PasswordReset': 'パスワードをリセットしてください',
  'Label.CheckEmail': 'メールを確認してください',
  'Label.ResendCode': 'コードを再送信に',
  'Label.Product': '製品',
  'Label.Description': '説明',
  'Label.Quantity': '量',
   'Label.Price': '価格',
   'Label.CartList': 'カートリスト',
   'Label.TotalPrice': '合計料金',
   'Label.TotalQuantity': '合計量',
   'Label.Tax': '税金',
   'Label.SubTotal': '小計',
   'Label.Information': '情報 ',
   'Label.ShippingInformation': '出荷情報',
   'Label.InformationDetail': '情報を完全に入力してください',
   'Label.OrderConfirm': '注文確認',
   'Label.OrderReview': '注文レビュー',
   'Button.Close': '閉じボタン',
   'Button.Shopping': 'ショッピング',
   'Label.Image': '画像',
   'Link.Detail': '詳細',
   'Button.Back': 'バック',
    'Label.OrderText': '**OrderIdで注文リストを検索できます**',
    'Label.DateText': '**Dateで注文リストを検索できます**',
    'Label.OrderHistory': '注文履歴',
    'Label.OrderSuccess': 'ご注文は完了しました...成功...!',
    'Label.OrderSuccessId': 'あなたの注文IDは',
     'Label.InfoDetail': '詳細情報',

   

  

};

export default ja;
